#pragma once
#include <string>
#include <vector>
#include <map>
#include <memory>

namespace SincroPro {

class DatabaseConnector {
public:
    virtual ~DatabaseConnector() = default;

    virtual bool connect(const std::string& connectionStringOrUrl) = 0;
    virtual void disconnect() = 0;
    virtual bool isConnected() const = 0;

    virtual std::vector<std::string> getTables() = 0;
    virtual std::vector<std::pair<std::string, std::string>> getColumns(const std::string& tableName) = 0;
    
    // Executes a read query (returns a list of rows, where each row is a map of columnName -> value)
    virtual std::vector<std::map<std::string, std::string>> executeQuery(const std::string& queryOrEndpoint) = 0;
    
    // Inserts data and returns the primary key/ID generated by the database (if any)
    virtual std::string executeInsert(const std::string& tableNameOrEndpoint, const std::map<std::string, std::string>& data) = 0;
    
    // Updates data based on a matching key
    virtual bool executeUpdate(const std::string& tableNameOrEndpoint, const std::map<std::string, std::string>& data, const std::string& keyColumn, const std::string& keyValue) = 0;
};

} // namespace SincroPro
